= Archive of alxdre301

== Về trang này

Đây là trang cá nhân thuộc sở hữu của alxdre301.

=== Câu hỏi mà chắc bạn sẽ hỏi

"Ai là alxdre301?"::
Một đứa ất ơ trên mạng, hãy đọc <<Biết thêm về mình>> để hiểu thêm.

"Trang này để làm gì?"::
Mình chiu, chắc chỉ cố gắng viết mấy thứ mình thích. Mình sẽ cố gắng viết thêm mấy cái bài viết ở đây.

"Tên miền của bạn có cái id.vn, cái đầy là cái gì thế?"::
id.vn là tên miền .vn cung cấp bởi VNNIC (viết tắt tiếng Anh của Trung tâm Internet Việt Nam). Hiện
tại, tên miền này cung cấp miễn phí tên miền cho người Việt Nam từ 18 đến 23 tuổi trong 2 năm. Xem
https://vnnic.vn/tenmien/hotro/cam-nang-ten-mien-idvn-0 để hiểu thêm.

== Biết thêm về mình

=== Thông tin cá nhân

Tên khác:: alxdre301, thanh9356, and 0x0F0F0F
Email:: alxdre301@gmail.com
Mạng xã hội::
* Mastodon: https://urusai.social/@alxdre301/[@alxdre301@urusai.social]
* Matrix: https://matrix.to/#/@alxdre301:4d2.org[@alxdre301:4d2.org]
* YouTube: https://www.youtube.com/@alxdre301[@alxdre301]
* GitHub: https://github.com/Thanh9356[Thanh9356]

=== Học tập

09-2024 — hiện tại::
* Sinh viên Trường Đại học Công nghệ Thông tin, ĐHQG-HCM
* Năm nhất ngành Kĩ thuật máy tính

=== Kinh nghiệm

2021 — 2023::
* Thành viên thuộc Cytoid Wiki
* Mình đã giúp Cytoid Wiki viết các bài tiếng Anh trong khoảng thời gian này.
* Kho Git: https://github.com/CytoidCommunity/Cytoid-wiki.git (đã lưu trữ)

=== Kĩ năng

T_T

=== Linh tinh

Rhythm games::
Mình chơi rhythm game cũng đã được 8 năm rồi, mình vẫn cố gắng duy trì thú vui này mỗi ngày. Dành
phần lớn thời gian chơi trên điện thoại.

Nhạc::
Mình có thể chịu được mọi loại nhạc nhưng mà mình có gu về giai điệu hơn là về lời nên là mình khá
là chậm hiểu "lời bài hát hay tới mức nào."

Anime & Manga::
Mình có gu tương đối tệ. Mình thường xem BL nhưng mà đôi lúc mình vẫn sẽ xem thể loại khác. Anime
thích nhất của mình là Psycho-Pass (mùa 1)

Nhân vật yêu thích::
Uenoyama Ritsuka (Given), Kogami Shinya (Psycho-Pass), Takamine Midori (Ensemble Stars!), Morisawa
Chiaki (Ensemble Stars!).

Thiết bị::
* nubia Neo 2 (Z2352N) (từ 09-2024)
* MSI Thin 15 B12UCX (từ 12-2024)
* Raspberry Pi Pico (từ 06-2023)
